---
language: node_js

node_js:
  - "5"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - "npm config set spin false"
  - "npm --version"

install:
  - "npm install"
  
script: npm run-script dist

# Send coverage data to Coveralls
after_script: "cat ./bin/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"